/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/saishi/saishi" |
       "/pages/login/login" |
       "/pages/more/more" |
       "/pages/saicheng/saicheng" |
       "/pages/saishi/personRegisition" |
       "/pages/saishi/registration-list" |
       "/pages/saishi/saishi-detail" |
       "/pages/saishi/teamRegisition" |
       "/pages/shequ/shequ" |
       "/pages/user/people" |
       "/pages-user/location/location" |
       "/pages-user/userEdit/userEdit";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/saishi/saishi" | "/pages/saicheng/saicheng" | "/pages/shequ/shequ" | "/pages/user/people"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
